name: lint pr

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    branches:
      - main

jobs:
  ruby_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Add comment
        uses: elasticspoon/test-action@main
        id: comment_pr
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
